# Generated by Django 2.2.28 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_icder'),
    ]

    operations = [
        migrations.AddField(
            model_name='icder',
            name='xaw',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
